---
- name: Deploy Wildfly
  hosts: wildfly
  remote_user: ec2-user
  become: yes
  gather_facts: no
  vars:
    epel_baseurl: https://download.fedoraproject.org/pub/epel/8/Everything/x86_64
    epel_rpm_key: https://src.fedoraproject.org/rpms/epel-release/raw/epel8/f/RPM-GPG-KEY-EPEL-8
    jboss_home_directory: /opt/jboss
    java_home_path: /usr/lib/jvm/java
    java_log_directory_path: /var/log/jboss
    java_opts: "-Xms1024m -Xmx20480m"
    java_path: /usr/bin/java
    jboss_home_path: /opt/jboss/wildfly
    wildfly_version: 26.0.0.Final
    wildfly_sha1: 836fdefc48b6008904b91b43e00bf6ee6d917486
  environment:
    JAVA_HOME: "{{ java_home_path }}"
    WILDFLY_VERSION: "{{ wildfly_version }}"
    WILDFLY_SHA1: "{{ wildfly_sha1 }}"
    JBOSS_HOME: "{{ jboss_home_path }}"
    LAUNCH_JBOSS_IN_BACKGROUND: true

  roles:
    - deploy_wildfly
