---
- name: Create elastic network interface
  amazon.aws.ec2_eni:
    private_ip_address: "{{ ec2_private_ip }}"
    subnet_id: "{{ vpc_subnet_id }}"
    region: "{{ aws_region }}"
    security_groups: "{{ security_group_name }}"
  register: ec2_instance_eni

- name: Deploy VM in AWS
  amazon.aws.ec2_instance:
    name: "{{ ec2_instance_name }}"
    key_name: "{{ aws_key }}"
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    network:
      interfaces:
        - id: "{{ ec2_instance_eni.interface.id }}"
      delete_on_termination: true
    instance_type: "{{ instance_type }}"
    image_id: "{{ ami_image }}"
    region: "{{ aws_region }}"
    state: running
