---
- name: Retrieve content of kubeconfig
  set_fact:
    kubeconfig: "{{ lookup('file', kubeconfig_file_path) }}"

- name: Generate required YAML definition files
  ansible.builtin.template:
    src: "templates/{{ item }}.yaml.j2"
    dest: "/tmp/{{ item }}.yaml"
  loop:
    - managed_cluster
    - auto_import_secret
    - klusterlet_addon_config
  delegate_to: localhost

- name: Create the namespace for the cluster to be imported
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ ocp_cluster_name }}"
    state: present
  delegate_to: localhost

- name: Add label to namespace of cluster to be imported
  kubernetes.core.k8s:
    state: patched
    kind: Namespace
    name: "{{ ocp_cluster_name }}"
    definition:
      metadata:
        labels:
          cluster.open-cluster-management.io/managedCluster: "{{ ocp_cluster_name }}"
  delegate_to: localhost

- name: Create Managed Cluster for import cluster
  kubernetes.core.k8s:
    state: present
    src: /tmp/managed_cluster.yaml
  delegate_to: localhost
      
- name: Create auto-import-secret for import cluster
  kubernetes.core.k8s:
    state: present
    src: /tmp/auto_import_secret.yaml
  delegate_to: localhost

- name: Import klusterlet
  kubernetes.core.k8s:
    state: present
    src: /tmp/klusterlet_addon_config.yaml
  delegate_to: localhost

- name: Wait for Cluster to be fully imported
  wait_for:
    timeout: 300
