---
- name: Gather facts of all Classic LB
  community.aws.elb_classic_lb_info:
    region: "{{ ocp_cluster_region }}"
  register: classic_elb_info

- ansible.builtin.set_fact:
    found_key: false

- include_tasks: wait_until_success.yaml
