---
- name: Initialize variable 'cluster_classic_lb_created' to false
  ansible.builtin.set_fact:
    cluster_classic_lb_created: false

- include_tasks: wait_until_cluster_classic_lb_created.yaml

#- name: Add '*.apps' record in AWS Route53 Hosted Zone
#  amazon.aws.route53:
#    state: present
#    zone: "."
#    hosted_zone_id: "{{ ocp_cluster_hosted_zone }}"
#    record: "*.apps.{{ ocp_cluster_name }}.{{ ocp_cluster_base_domain }}"
#    type: A
#    value: "{{ cluster_classic_lb }}"
#    alias: true
#    alias_hosted_zone_id: "{{ ocp_cluster_alias_hosted_zone }}"
#    alias_evaluate_target_health: true
