---
- name: Gather facts of all Classic LB
  community.aws.elb_classic_lb_info:
    region: "{{ ocp_cluster_region }}"
  register: classic_elb_info

- ansible.builtin.set_fact:
    found_key: false

- name: Wait till success
  block:
    - name: Set the retry count
      set_fact:
        retry_count: "{{ 0 if retry_count is undefined else retry_count|int + 1 }}"

    - debug:
        var: found_key
  rescue:
    - fail:
        msg: Ended after 5 retries
      when: retry_count|int == 5

    - debug:
        msg: "Failed to connect - Retrying..."

    - include_tasks: check_classic_loadbalancer_tags.yaml
      loop: "{{ range(0, classic_elb_info.elbs | length) | list }}"
      loop_control:
        loop_var: _tag
