---
- name: Wait until cluster classic load balancer is created
  block:
    - name: Set retry count
      ansible.builtin.set_fact:
        retry_count: "{{ 0 if retry_count is undefined else retry_count | int + 1 }}"

    - name: Gather facts of all Classic LB
      community.aws.elb_classic_lb_info:
        region: "{{ ocp_cluster_region }}"
      register: classic_elb_info

    - include_tasks: check_classic_loadbalancer_tags.yaml
      loop: "{{ range(0, classic_elb_info.elbs | length) | list }}"
      loop_control:
        loop_var: _tag

    - ansible.builtin.debug:
        var: cluster_classic_lb_created
      failed_when: cluster_classic_lb_created == false

  rescue:
    - ansible.builtin.fail:
        msg: Deployment is expected to complete within 90 mins - Wait for at most 30 retries
      when: retry_count | int == 30

    - ansible.builtin.debug:
        msg: "Cluster Load Balancer Not Created Yet - Retrying after 3 minutes..."

    - name: Sleep for 3 minutes
      ansible.builtin.wait_for:
        timeout: 180
    
    - include_tasks: wait_until_cluster_classic_lb_created.yaml
