---
- name: Get all existing Namespaces
  kubernetes.core.k8s_info:
    kind: Namespace
  register: ns_list
  delegate_to: localhost

- debug:
    var: ns_list.resources[item].name
  loop: "{{ range(0, ns_list.resources | length) | list }}" 

- name: Create cluster namespace
  kubernetes.core.k8s:
    name: "{{ ocp_cluster_name }}"
    api_version: v1
    kind: Namespace
    state: present
    validate_certs: false
  delegate_to: localhost

- name: Create secret for Hive Deployment
  kubernetes.core.k8s:
    state: present
    src: "{{ install_directory }}/{{ ocp_cluster_name }}-credentials-requests/bound-service-account-signing-key.yaml"

- name: Create Configmap for Hive Deployment
  kubernetes.core.k8s:
    state: present
    src: "{{ install_directory }}/cluster-manifests.yaml"
