---
- name: Get all existing Namespaces
  kubernetes.core.k8s_info:
    kind: Namespace
  register: ocp_namespaces
  delegate_to: localhost

- name: Define namespace list
  ansible.builtin.set_fact:
    ns_list: "{{ ocp_namespaces.resources }}"

- name: Fail task if cluster namespace already exists
  ansible.builtin.fail:
    msg: "{{ ocp_cluster_name }} already exists! Please check before proceeding!" 
  when: ocp_cluster_name == ns_list[item].metadata.name
  loop: "{{ range(0, ns_list | length) | list }}" 

- name: Create cluster namespace
  kubernetes.core.k8s:
    name: "{{ ocp_cluster_name }}"
    api_version: v1
    kind: Namespace
    state: present
    validate_certs: false
  delegate_to: localhost

- name: Fetch secret and configmap YAML Files from Helper Node
  ansible.builtin.fetch:
    src: "{{ item }}"
    dest: "{{ temporary_directory }}"
    flat: yes
  loop:
    - "{{ install_directory }}/{{ ocp_cluster_name }}-credentials-requests/bound-service-account-signing-key.yaml"
    - "{{ install_directory }}/cluster-manifests.yaml"
 
- name: Create secret for Hive Deployment
  kubernetes.core.k8s:
    state: present
    src: "{{ temporary_directory }}/bound-service-account-signing-key.yaml"
  delegate_to: localhost

- name: Create Configmap for Hive Deployment
  kubernetes.core.k8s:
    state: present
    src: "{{ temporary_directory }}/cluster-manifests.yaml"
  delegate_to: localhost
